Update ci-cd.yml

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -32,11 +32,16 @@ jobs:
 
     - name: Run Container
       run: |
+        docker rm -f flask-app || true
         docker run -d -p 5000:5000 --name flask-app \
         ${{ secrets.DOCKER_USERNAME }}/flask-app:latest
 
         sleep 5
         docker ps -a
+
+    - name: Check logs
+      run: docker logs flask-app
+        
 
     - name: Wait for App
       run: sleep 20
@@ -49,18 +54,18 @@ jobs:
 
     - name: Test Application
       run: |
-        for i in {1..8}; do
-          echo "Attempt $i..."
-          if curl -v http://localhost:5000; then
-            echo "SUCCESS"
-            exit 0
-          fi
+        echo "Waiting for app..."
+        sleep 10
+
+        for i in {1..5}; do
+          echo "Attempt $i"
+          curl -v http://localhost:5000 && exit 0
           sleep 5
         done
 
-        echo "FAILED TO CONNECT"
+        echo "FAILED"
         docker ps -a
-        docker logs flask-app || true
+        docker logs flask-app
         exit 1
       
   notify:
